### ISSUE TITLE
postgres_user:present: Add support for scram-sha-256

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/salt#258]
### Description of Issue/Question

Creating a postgres user with:

```
p:
  postgres_user.present:
    - name: wurst
    - password: brot
    - encrypted: True
```

only supports md5 and not scram-sha256! I would expect something like:

```
p:
  postgres_user.present:
    - name: wurst
    - password: brot
    - encryption: no|md5|scam-sha-256
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.4.6
      pycparser: 2.17
       pycrypto: 3.9.0
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.3.18-lp152.36-default
         system: Linux
        version: Not Installed
```
