### ISSUE TITLE
saltstack server_id changes with each run on python3 backport patch

### ISSUE THREAD

**Issue by aboe76** [openSUSE/salt#94]
### Description of Issue/Question
saltstack server_id changes with each run

### Setup
Opensuse Tumbleweed

### Steps to Reproduce Issue
install tumbleweed, install salt-master, salt-minion, exchange keys,
run salt-call grains.item server_id multiple times

```
[root@example.com stack (master)]# salt-call grains.item server_id && date
local:
    ----------
    server_id:
        812924806

[root@example.com stack (master)]# salt-call grains.item server_id && date
local:
    ----------
    server_id:
        533218382
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 3.3.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 3.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.17.2-1-default
         system: Linux
        version: Not Installed
```

This was fixed in:

https://github.com/saltstack/salt/pull/46649
